set(VERSION_MAJOR 77)
set(VERSION_MINOR 1)
set(VERSION "${VERSION_MAJOR}.${VERSION_MINOR}")
set(VERSION2 "${VERSION_MAJOR}_${VERSION_MINOR}")
set(VERSION3 "${VERSION_MAJOR}-${VERSION_MINOR}")

set(FILENAME "icu4c-${VERSION2}-src.tgz")
set(URLS "https://github.com/unicode-org/icu/releases/download/release-${VERSION3}/${FILENAME}")

# Get archive
vcpkg_download_distfile(ARCHIVE
    URLS ${URLS}
    FILENAME ${FILENAME}
    SHA512 a47d6d9c327d037a05ea43d1d1a06b2fd757cc02a94f7c1a238f35cfc3dfd4ab78d0612790f3a3cca0292c77412a9c2c15c8f24b718f79a857e007e66f07e7cd
)

# Patches
set(PATCHES
    # CMake build system (third-party LibCMaker)
    ${CMAKE_CURRENT_LIST_DIR}/patches/0001-Add-CMake-platform.patch
    # vcpkg fixup: remove bin64/lib64 install suffix on Windows
    ${CMAKE_CURRENT_LIST_DIR}/patches/0002-Remove-install-suffix-on-Windows.patch
    # Cross-compilation support for CMake build files
    ${CMAKE_CURRENT_LIST_DIR}/patches/0003-Support-cross-compilation-in-CMake-build.patch
    # Cross-compilation support for pkgdata tool
    ${CMAKE_CURRENT_LIST_DIR}/patches/0004-Cross-compilation-support-for-pkgdata.patch
)

# Extract archive
vcpkg_extract_source_archive_ex(
    OUT_SOURCE_PATH SOURCE_PATH
    ARCHIVE ${ARCHIVE}
    PATCHES ${PATCHES}
)

# Run CMake build
set(BUILD_OPTIONS
    -DICU_ENABLE_PLUGINS=OFF
    -DICU_ENABLE_EXTRAS=OFF
    -DICU_ENABLE_SAMPLES=OFF
    -DICU_ENABLE_TESTS=OFF
)

# When cross-compiling from a non-Windows host (e.g. Linux -> Windows), build
# native host tools first, then use them for the cross-compile. This avoids
# needing Wine to run cross-compiled .exe tools.
if (VCPKG_CROSSCOMPILING AND NOT VCPKG_HOST_IS_WINDOWS AND NOT DEFINED ICU_CROSS_BUILD_ROOT)
    message(STATUS "Building native ICU host tools for cross-compilation...")
    set(HOST_BUILD_DIR "${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-host")

    # Use ICU's autotools build for the native host tools. The CMake build
    # system (from patch 0001) has bugs that only manifest on native Linux
    # (lowercase list(append), missing sources.txt for escapesrc), so autotools
    # is more reliable here. The resulting bin/ layout is the same either way.
    file(MAKE_DIRECTORY "${HOST_BUILD_DIR}")
    execute_process(
        COMMAND "${CMAKE_COMMAND}" -E env --unset=CC --unset=CXX --unset=CFLAGS --unset=CXXFLAGS --unset=LDFLAGS
            "${SOURCE_PATH}/source/configure"
            --disable-shared --enable-static
            --disable-extras --disable-icuio
            --disable-layout --disable-layoutex
            --disable-tests --disable-samples
        WORKING_DIRECTORY "${HOST_BUILD_DIR}"
        COMMAND_ERROR_IS_FATAL ANY
    )
    include(ProcessorCount)
    ProcessorCount(NPROC)
    if (NPROC EQUAL 0)
        set(NPROC 1)
    endif ()
    execute_process(
        COMMAND make -j${NPROC}
        WORKING_DIRECTORY "${HOST_BUILD_DIR}"
        COMMAND_ERROR_IS_FATAL ANY
    )

    set(ICU_CROSS_BUILD_ROOT "${HOST_BUILD_DIR}")

    # The CMake cross-compile system expects config/icucross.cmake in the host
    # build root (normally generated by a CMake host build). Since we used
    # autotools, generate it manually. It just sets TOOLBINDIR and TOOLLIBDIR.
    file(MAKE_DIRECTORY "${HOST_BUILD_DIR}/config")
    file(WRITE "${HOST_BUILD_DIR}/config/icucross.cmake"
        "set(CROSS_ICU_VERSION ${VERSION})\n"
        "set(TOOLBINDIR \${ICU_CROSS_BUILDROOT}/bin)\n"
        "set(TOOLLIBDIR \${ICU_CROSS_BUILDROOT}/lib)\n"
    )

    # Patch 0003 appends CMAKE_EXECUTABLE_SUFFIX (.exe) to tool paths in the
    # data CMakeLists.txt. CMake's Windows platform module forces this to .exe,
    # overriding any cache variable. Create .exe symlinks so the suffixed paths
    # resolve to the native Linux binaries.
    set(HOST_TOOLS icupkg pkgdata genrb genccode gencmn gennorm2 gensprep
                   makeconv genbrk gencfu gencnval gendict)
    foreach (tool ${HOST_TOOLS})
        if (EXISTS "${HOST_BUILD_DIR}/bin/${tool}" AND NOT EXISTS "${HOST_BUILD_DIR}/bin/${tool}.exe")
            file(CREATE_LINK "${HOST_BUILD_DIR}/bin/${tool}" "${HOST_BUILD_DIR}/bin/${tool}.exe" SYMBOLIC)
        endif ()
    endforeach ()
endif ()

# Check for a cross compile
if (DEFINED ICU_CROSS_BUILD_ROOT)
    message(STATUS "Cross compiling ICU")

    set(CROSS_COMPILING ON)
    set(ENABLE_TOOLS OFF)

    # Place value of ICU_CROSS_BUILDROOT into the triplet file
    list(APPEND BUILD_OPTIONS -DICU_CROSS_BUILDROOT=${ICU_CROSS_BUILD_ROOT})
else ()
    set(CROSS_COMPILING OFF)
    set(ENABLE_TOOLS ON)
endif ()

# When building from a non-Windows host, pkgdata cannot invoke link.exe/LIB.exe.
# The CMake build links the data library itself, so skip the redundant link step
# in pkgdata (patch 0006). This applies whether tools are built locally or
# pre-built native host tools are used via ICU_CROSS_BUILD_ROOT.
if (NOT VCPKG_HOST_IS_WINDOWS)
    set(ENV{ICU_SKIP_PKGDATA_LINK} 1)

    # Tell the native Linux pkgdata binary which CPU architecture to target
    # when generating COFF object code (patch 0005). On native Windows the
    # _M_* macros handle this, but a Linux-built pkgdata needs the env var.
    if (VCPKG_TARGET_ARCHITECTURE STREQUAL "arm64")
        set(ENV{ICU_DATA_CPU_ARCH} "arm64")
    elseif (VCPKG_TARGET_ARCHITECTURE STREQUAL "x64")
        set(ENV{ICU_DATA_CPU_ARCH} "x64")
    elseif (VCPKG_TARGET_ARCHITECTURE STREQUAL "x86")
        set(ENV{ICU_DATA_CPU_ARCH} "x86")
    endif ()
endif ()

vcpkg_cmake_configure(
    SOURCE_PATH ${SOURCE_PATH}/source
    OPTIONS
        ${BUILD_OPTIONS}
        -DICU_ENABLE_TOOLS=${ENABLE_TOOLS}
        -DICU_CROSS_COMPILING=${CROSS_COMPILING}
)

vcpkg_cmake_install()
vcpkg_copy_pdbs()
vcpkg_cmake_config_fixup(CONFIG_PATH lib/cmake/ICU)
vcpkg_fixup_pkgconfig()

if (ENABLE_TOOLS)
    # Rearrange location of tools
    set(TOOLS
        genbrk
        gencfu
        gencnval
        gendict
        genrb
        gentest
        pkgdata
        makeconv
        icuinfo
    )
    set(STOOLS
        genccode
        gencmn
        gennorm2
        gensprep
        icupkg)

    set(TOOL_EXTENSION .exe)

    file(MAKE_DIRECTORY ${CURRENT_PACKAGES_DIR}/tools/icu)

    foreach (tool ${TOOLS})
        # Remove debug versions
        file(REMOVE ${CURRENT_PACKAGES_DIR}/debug/bin/${tool}${TOOL_EXTENSION})
        # Move into the tools directory
        file(RENAME ${CURRENT_PACKAGES_DIR}/bin/${tool}${TOOL_EXTENSION} ${CURRENT_PACKAGES_DIR}/tools/icu/${tool}${TOOL_EXTENSION})
    endforeach()
    foreach (tool ${STOOLS})
        # Remove debug versions
        file(REMOVE ${CURRENT_PACKAGES_DIR}/debug/sbin/${tool}${TOOL_EXTENSION})
        # Move into the tools directory
        file(RENAME ${CURRENT_PACKAGES_DIR}/sbin/${tool}${TOOL_EXTENSION} ${CURRENT_PACKAGES_DIR}/tools/icu/${tool}${TOOL_EXTENSION})
    endforeach()

    # vcpkg_copy_tool_dependencies requires PowerShell, skip on non-Windows hosts
    if (VCPKG_HOST_IS_WINDOWS)
        vcpkg_copy_tool_dependencies(${CURRENT_PACKAGES_DIR}/tools/icu)
    endif ()
endif ()

# Prepare distribution
file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/debug/include)
file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/debug/share)
file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/debug/sbin)
file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/sbin)

# Meson requires a pkgconfig file to properly build libraries with ICU
# The CMake here doesn't create one so just use a generated one
if (VCPKG_TARGET_IS_WINDOWS)
    file(INSTALL ${CMAKE_CURRENT_LIST_DIR}/pkgconfig/release DESTINATION ${CURRENT_PACKAGES_DIR}/lib RENAME pkgconfig)
    file(INSTALL ${CMAKE_CURRENT_LIST_DIR}/pkgconfig/debug DESTINATION ${CURRENT_PACKAGES_DIR}/debug/lib RENAME pkgconfig)
endif ()

file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/icu RENAME copyright)
file(WRITE ${CURRENT_PACKAGES_DIR}/share/icu/version "${VERSION_MAJOR}.${VERSION_MINOR}.0")
